### ISSUE TITLE
Dependencies not checked for dependencies

### ISSUE THREAD

**Issue by thePalindrome** [Vazkii/CMPDL#16]
Many mod packs require Thermal Expansion et al. but don't directly depend on CoFH Core.
Because dependencies are only checked for the modpack, this means that several packs (an example being https://minecraft.curseforge.com/projects/the-lone-survivor ) require the additional step of grabbing CoFH Core.

**Comment by Nincodedo** [comment]
CoFH Core is in the manifest for that modpack, however the specific version of CoFH Core that this modpack references no longer exists.

```
{
      "projectID": 69162,
      "fileID": 2283118,
      "required": true
}
```
That's the CoFH Core part in the manifest, which correlates to this download link...

https://minecraft.curseforge.com/projects/cofhcore/files/2283118/download

Which doesn't exist. Not much that can be done about this besides updating the modpack to use files that are still on Curse.

**Comment by thePalindrome** [comment]
Ah, my bad. Given the symptoms I assumed dependency resolution was the issue :P 

Alas, I have no idea what the official launcher does in that situation, since "latest" isn't an option ( since some mods might have a latest for 1.10, which isn't compatible with 1.7.10)

**Comment by Nincodedo** [comment]
No problem! It seems the official launcher can sometimes still download files like this depending if they were just hidden or actually deleted by the mod author.

**Comment by Silent-Hunter** [comment]
This could be a big problem though, if my friend has Windows, and used the official client, and I have Linux, and had to use this, I have to get different versions of these missing mods, doesn't that mean we can't play together? Or will it just work anyway even though we have different versions?

**Comment by Nincodedo** [comment]
Well you can get the missing mods from your friend if he was able to get them.

**Comment by Silent-Hunter** [comment]
Oh good point.

**Comment by Vazkii** [comment]
There really isn't anything I can do if the files were removed. Curse has
access to that stuff, but I'm not curse.
