### ISSUE TITLE
Download trips on a caret sign.

### ISSUE THREAD

**Issue by AssasinAsha** [Vazkii/CMPDL#3]
Tried downloading [Material Energy^Natural Capital](https://mods.curse.com/modpacks/minecraft/236723-material-energy-natural-capital#t1:other-downloads), but since it uses that one character in the name...

> ~ Starting magical modpack download sequence ~
> Error: Illegal character in path at index 59: http://addons.cursecdn.com/files/2318/810/Material%20Energy^Natural%20Capital-0.11.04.zip
> java.net.URI$Parser.fail(URI.java:2848)
> java.net.URI$Parser.checkChars(URI.java:3021)
> java.net.URI$Parser.parseHierarchical(URI.java:3105)
> java.net.URI$Parser.parse(URI.java:3053)
> java.net.URI.<init>(URI.java:588)
> vazkii.cmpdl.CMPDL.getLocationHeader(CMPDL.java:286)
> vazkii.cmpdl.CMPDL.downloadFromURL(CMPDL.java:58)
> vazkii.cmpdl.OperatorThread.run(OperatorThread.java:17)

By the way, thank you for doing an amazing job with this.

**Comment by thePalindrome** [comment]
Not sure if this has been fixed yet, but I'll just mention the carat is 5E when escaping. Save someone some time :P

**Comment by thePalindrome** [comment]
This bug was fixed a month ago as part of 1.1.3, Requesting a close.
