### ISSUE TITLE
Problem with " ' " or "+" in names

### ISSUE THREAD

**Issue by voron3d** [Vazkii/CMPDL#40]
When download mods like "Tinkers'+Addons-1.12.1-1.0.7.jar" you get "Tinkers%27 Addons-1.12.1-1.0.7.jar" and file with 0 size. 
"angelRingToBauble-1.12-0.3.1.50%2Bd4e654e.jar" you get
"angelRingToBauble-1.12-0.3.1.50+d4e654e.jar" and 0 size.
Try ti get woth gie this "Pam's+HarvestCraft+1.12.2o.jar"  ))

**Comment by syntaxer** [comment]
Why is this closed.. This is still an issue
