### ISSUE TITLE
File already exists, No need to download it

### ISSUE THREAD

**Issue by DauidBeck** [Vazkii/CMPDL#50]
This is my first time using CMPDL and i got this issue

Downloading 239431/2290798
Project URL is http://minecraft.curseforge.com/projects/239431
File download URL is https://minecraft.curseforge.com/projects/mcmultipart/files/2290798/download
Downloading MCMultiPart-1.1.1-universal.jar
This file already exists. No need to download it
Downloaded! 37/64 remaining

The file DOESNT exist. but CMPDL thinks it does... What can i do to solve this? 
I'm on Debian 9

**Comment by DauidBeck** [comment]
This also happened with all other mods. Only 4 files were actually downloaded

**Comment by frenchiveruti** [comment]
Try using MultiMC instead!
