### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by coopw1** [Vazkii/CMPDL#63]
The program is trying to download each modpack through https://www.curseforge.com/minecraft/modpacks/Modpack/files/versionID/download when it should be downloaded through https://www.curseforge.com/minecraft/modpacks/Modpack/files/download/versionID/

**Comment by rantNYC** [comment]
+1 to this. I've tried the latest version but it doesn't work due to the format change

**Comment by ajfite** [comment]
+1 its completely broken

**Comment by Vazkii** [comment]
Did they really change this again? It's time to stop pls

I'll have a look at it when I get home.

**Comment by bentalexanderhaase** [comment]
Thank you @Vazkii in advance! This is insanity - they should just provide a "download modpack as zip" button on their page for every modpack. Forcing users into their launcher purely for money is bad practice. We just want to game - we want to chose how we want to game....

Sorry for the rant :(

**Comment by coopw1** [comment]
@BentHaase Completely agree, thanks @Vazkii for doing this, its a big help.

**Comment by Vazkii** [comment]
Updated in 1.2.2
