### ISSUE TITLE
They changed it again xD

### ISSUE THREAD

**Issue by m00nwtchr** [Vazkii/CMPDL#66]
In the download url they removed the "/files/" part

e.g. https://www.curseforge.com/minecraft/modpacks/rlcraft/files/download/2791782 is now https://www.curseforge.com/minecraft/modpacks/rlcraft/download/2791782

**Comment by humroben** [comment]
I can confirm, I'm trying to get foolcraft 3 installed, and hitting the same issue. I really wish twitch/curseforge would stop changing it so much.

**Comment by humroben** [comment]
I did compile the current master branch, and it does cover this, however the next issue is Cloudflare

**Comment by lukas2005** [comment]
Yeah i tried that too and ran into it

**Comment by coopw1** [comment]
Yeah, they just keep changing the link format.

**Comment by bentalexanderhaase** [comment]
> I did compile the current master branch, and it does cover this, however the next issue is Cloudflare

They are pretty much:

'*We don't want any Linux gamer*'. - twitch 2019

**Comment by m00nwtchr** [comment]
Yep i did the same and Cloudflare is just making things hard

**Comment by stefnotch** [comment]
https://github.com/iTitus/CMPDL/releases/tag/v1.3.0 seems to currently work
